/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.*;
import javax.swing.JOptionPane;
import dao.ConexaoApiPython;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.awt.*;
/**
 *
 * @author gabri
 */

public class cadastroUsuarios extends javax.swing.JFrame {

    //private JLabel backgroundLabel;
    private String caminhoImagem;
    /**
     * Creates new form cadastroUsuarios
     */
    public cadastroUsuarios() {
        initComponents();
        setLocationRelativeTo(null);
        setBackgroundImage();
        setTitle("Cadastro - Senac Hub Academy");
        ImageIcon icon = new ImageIcon("\"C:\\Users\\gabri\\Downloads\\logo_sneac-removebg-preview.png\"");


    }

    private void setBackgroundImage() {
        // Painel com imagem de fundo
        JPanel contentPane = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                ImageIcon backgroundIcon = new ImageIcon("C:\\Users\\gabri\\Downloads\\HomeBAKGROUND2.png");
                Image img = backgroundIcon.getImage();
                g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            }
        };

        // Configurações do painel principal
        contentPane.setLayout(new BorderLayout());
        setContentPane(contentPane);

        // Torna o jPanel1 transparente e adiciona ao painel principal
        jPanel1.setOpaque(false);

        contentPane.add(jPanel1);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        groupCategory = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();
        inputEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnSelecionarImagem = new javax.swing.JButton();
        inputTelefone = new javax.swing.JTextField();
        inputNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setForeground(new java.awt.Color(0, 0, 153));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cadastro de Usuários");
        jLabel2.setName(""); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 320, 40));

        btnListar.setBackground(new java.awt.Color(0, 102, 102));
        btnListar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setText("Listar Usuários");
        btnListar.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        jPanel1.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 580, 200, 50));

        inputEmail.setBackground(new java.awt.Color(51, 0, 51));
        inputEmail.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        inputEmail.setForeground(new java.awt.Color(255, 255, 255));
        inputEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputEmail.setAlignmentX(2.0F);
        inputEmail.setAutoscrolls(false);
        inputEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 7, 1, 3));
        inputEmail.setCaretColor(new java.awt.Color(102, 255, 255));
        inputEmail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inputEmail.setDoubleBuffered(true);
        inputEmail.setMargin(new java.awt.Insets(8, 50, 8, 50));
        inputEmail.setNextFocusableComponent(inputEmail);
        inputEmail.setOpaque(true);
        inputEmail.setSelectionColor(new java.awt.Color(102, 204, 255));
        inputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEmailActionPerformed(evt);
            }
        });
        jPanel1.add(inputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 260, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 50, 30));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nome");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 50, 30));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefone");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 80, 30));

        btnCadastrar.setBackground(new java.awt.Color(0, 102, 102));
        btnCadastrar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 580, 200, 50));

        btnSelecionarImagem.setBackground(new java.awt.Color(204, 204, 204));
        btnSelecionarImagem.setForeground(new java.awt.Color(51, 51, 51));
        btnSelecionarImagem.setText("Escolha o arquivo");
        btnSelecionarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarImagemActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelecionarImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, 480, 140));

        inputTelefone.setBackground(new java.awt.Color(51, 0, 51));
        inputTelefone.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        inputTelefone.setForeground(new java.awt.Color(255, 255, 255));
        inputTelefone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputTelefone.setAlignmentX(2.0F);
        inputTelefone.setAutoscrolls(false);
        inputTelefone.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 7, 1, 3));
        inputTelefone.setCaretColor(new java.awt.Color(102, 255, 255));
        inputTelefone.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inputTelefone.setDoubleBuffered(true);
        inputTelefone.setMargin(new java.awt.Insets(8, 50, 8, 50));
        inputTelefone.setNextFocusableComponent(inputEmail);
        inputTelefone.setOpaque(true);
        inputTelefone.setSelectionColor(new java.awt.Color(102, 204, 255));
        inputTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTelefoneActionPerformed(evt);
            }
        });
        jPanel1.add(inputTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 260, 40));

        inputNome.setBackground(new java.awt.Color(51, 0, 51));
        inputNome.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        inputNome.setForeground(new java.awt.Color(255, 255, 255));
        inputNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputNome.setAlignmentX(2.0F);
        inputNome.setAutoscrolls(false);
        inputNome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 7, 1, 3));
        inputNome.setCaretColor(new java.awt.Color(102, 255, 255));
        inputNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        inputNome.setDoubleBuffered(true);
        inputNome.setMargin(new java.awt.Insets(8, 50, 8, 50));
        inputNome.setNextFocusableComponent(inputEmail);
        inputNome.setOpaque(true);
        inputNome.setSelectionColor(new java.awt.Color(102, 204, 255));
        inputNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNomeActionPerformed(evt);
            }
        });
        jPanel1.add(inputNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 260, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1132, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void inputEmailActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        
        String[] colunas={"Nome", "Email", "Telefone"};
        
        Object[][] dados = {
        {"Gabriel", "gabriel@example.com", "123456789"},
        {"Maria", "maria@example.com", "987654321"},
        {"João", "joao@example.com", "456123789"}
    };
        
//        JTable tabelaUsuarios = new JTable(dados, colunas);
//        
//        JScrollPane scrollPane = new JScrollPane(tabelaUsuario);
        
        
        
    }
    
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String nome = inputNome.getText();
        String email = inputEmail.getText();
        String telefone = inputTelefone.getText();

        //validar campos vazios
        if(nome.isEmpty() || email.isEmpty() || telefone.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos os campos são obrigatórios!");
            return;
        }

        //validar iumagem selecionada
        if(caminhoImagem == null || caminhoImagem.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione uma imagem!");
            return;
        }
        
        if (!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um e-mail válido!");
            return;
        }

        if (!telefone.matches("^\\d{10,11}$")) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um telefone válido (somente números)!");
            return;
        }


        //criar arquivo
        File foto = new File(caminhoImagem);

        //enviar dados para a API
        try{
            ConexaoApiPython.enviarDados(nome, email, telefone, foto);
            JOptionPane.showMessageDialog(this, "Cadastro Realizado com sucesso!");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar: " + ex.getMessage());
        }

    }

    private void btnSelecionarImagemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fileChooser.setDialogTitle("Selecione uma imagem");

        //abrir direto no Downloads
        File downloadsPaste = new File(System.getProperty("user.home") + "Downloads");
        fileChooser.setCurrentDirectory(downloadsPaste);

        // Filtro para aceitar apenas arquivos de imagem (JPG, PNG)
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagens (JPG, PNG)", "jpg", "jpeg", "png");
        fileChooser.setFileFilter(filtro);

        // Mostrar o dialog para seleção do arquivo
        int resultado = fileChooser.showOpenDialog(this);

        // Verificar se o usuário selecionou um arquivo
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File imagemSelecionada = fileChooser.getSelectedFile();
            caminhoImagem = imagemSelecionada.getAbsolutePath();
            JOptionPane.showMessageDialog(this, "Imagem selecionada: " + caminhoImagem);
        }
    }

    private void inputTelefoneActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void inputNomeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
    }
    // Variables declaration - do not modify
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSelecionarImagem;
    private javax.swing.ButtonGroup groupCategory;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputTelefone;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        @Override
        public void run() {
            new cadastroUsuarios().setVisible(true);
        }
    }
}